//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A message being returned to sender or otherwise rerouted after problems.
 * 
 * <p>Java class for DeadMessageV2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeadMessageV2Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}Message">
 *       &lt;sequence>
 *         &lt;element name="ReasonV2" type="{http://xml.networkrail.co.uk/ns/2008/EAI}EventV2"/>
 *         &lt;element name="OriginalMessageV2" type="{http://xml.networkrail.co.uk/ns/2008/EAI}ShortDescriptionType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeadMessageV2Type", propOrder = {
    "reasonV2",
    "originalMessageV2"
})
@XmlSeeAlso({
    DeadMessageV2 .class
})
public class DeadMessageV2Type
    extends Message
{

    @XmlElement(name = "ReasonV2", required = true)
    protected EventV2 reasonV2;
    @XmlElement(name = "OriginalMessageV2", required = true)
    protected ShortDescriptionType originalMessageV2;

    /**
     * Gets the value of the reasonV2 property.
     * 
     * @return
     *     possible object is
     *     {@link EventV2 }
     *     
     */
    public EventV2 getReasonV2() {
        return reasonV2;
    }

    /**
     * Sets the value of the reasonV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventV2 }
     *     
     */
    public void setReasonV2(EventV2 value) {
        this.reasonV2 = value;
    }

    /**
     * Gets the value of the originalMessageV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ShortDescriptionType }
     *     
     */
    public ShortDescriptionType getOriginalMessageV2() {
        return originalMessageV2;
    }

    /**
     * Sets the value of the originalMessageV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortDescriptionType }
     *     
     */
    public void setOriginalMessageV2(ShortDescriptionType value) {
        this.originalMessageV2 = value;
    }

}
