//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="technical"/>
 *     &lt;enumeration value="application"/>
 *     &lt;enumeration value="user"/>
 *     &lt;enumeration value="security"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventCategory")
@XmlEnum
public enum EventCategory {

    @XmlEnumValue("technical")
    TECHNICAL("technical"),
    @XmlEnumValue("application")
    APPLICATION("application"),
    @XmlEnumValue("user")
    USER("user"),
    @XmlEnumValue("security")
    SECURITY("security");
    private final String value;

    EventCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventCategory fromValue(String v) {
        for (EventCategory c: EventCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
