//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * An occurence worthy of logging.
 * 
 * <p>Java class for EventV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Source" type="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor"/>
 *         &lt;element name="ShortDescriptionV2" type="{http://xml.networkrail.co.uk/ns/2008/EAI}ShortDescriptionType"/>
 *         &lt;element name="LongDescriptionV2" type="{http://xml.networkrail.co.uk/ns/2008/EAI}LongDescriptionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="category" use="required" type="{http://xml.networkrail.co.uk/ns/2008/EAI}EventCategory" />
 *       &lt;attribute name="severity" use="required" type="{http://xml.networkrail.co.uk/ns/2008/EAI}EventSeverity" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="eventId" use="required" type="{http://xml.networkrail.co.uk/ns/2008/EAI}rfc2822id" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventV2", propOrder = {
    "source",
    "shortDescriptionV2",
    "longDescriptionV2"
})
public class EventV2 {

    @XmlElement(name = "Source", required = true)
    protected MsgActor source;
    @XmlElement(name = "ShortDescriptionV2", required = true)
    protected ShortDescriptionType shortDescriptionV2;
    @XmlElement(name = "LongDescriptionV2", required = true)
    protected LongDescriptionType longDescriptionV2;
    @XmlAttribute(name = "category", required = true)
    protected EventCategory category;
    @XmlAttribute(name = "severity", required = true)
    protected EventSeverity severity;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "eventId", required = true)
    protected String eventId;
    @XmlAttribute(name = "type")
    @XmlSchemaType(name = "anyURI")
    protected String type;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link MsgActor }
     *     
     */
    public MsgActor getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgActor }
     *     
     */
    public void setSource(MsgActor value) {
        this.source = value;
    }

    /**
     * Gets the value of the shortDescriptionV2 property.
     * 
     * @return
     *     possible object is
     *     {@link ShortDescriptionType }
     *     
     */
    public ShortDescriptionType getShortDescriptionV2() {
        return shortDescriptionV2;
    }

    /**
     * Sets the value of the shortDescriptionV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortDescriptionType }
     *     
     */
    public void setShortDescriptionV2(ShortDescriptionType value) {
        this.shortDescriptionV2 = value;
    }

    /**
     * Gets the value of the longDescriptionV2 property.
     * 
     * @return
     *     possible object is
     *     {@link LongDescriptionType }
     *     
     */
    public LongDescriptionType getLongDescriptionV2() {
        return longDescriptionV2;
    }

    /**
     * Sets the value of the longDescriptionV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongDescriptionType }
     *     
     */
    public void setLongDescriptionV2(LongDescriptionType value) {
        this.longDescriptionV2 = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link EventCategory }
     *     
     */
    public EventCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventCategory }
     *     
     */
    public void setCategory(EventCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link EventSeverity }
     *     
     */
    public EventSeverity getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSeverity }
     *     
     */
    public void setSeverity(EventSeverity value) {
        this.severity = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the eventId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventId(String value) {
        this.eventId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
