//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}Message">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/EAI}GeneralMsg"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generalMsg"
})
@XmlRootElement(name = "GeneralMsgV1")
public class GeneralMsgV1
    extends Message
{

    @XmlElement(name = "GeneralMsg", required = true)
    protected GeneralMsg generalMsg;

    /**
     * Gets the value of the generalMsg property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralMsg }
     *     
     */
    public GeneralMsg getGeneralMsg() {
        return generalMsg;
    }

    /**
     * Sets the value of the generalMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralMsg }
     *     
     */
    public void setGeneralMsg(GeneralMsg value) {
        this.generalMsg = value;
    }

}
