//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A message sent to log an event.
 * 
 * <p>Java class for LogMessageV2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogMessageV2Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}Message">
 *       &lt;sequence>
 *         &lt;element name="EventV2" type="{http://xml.networkrail.co.uk/ns/2008/EAI}EventV2" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogMessageV2Type", propOrder = {
    "eventV2"
})
@XmlSeeAlso({
    LogMessageV2 .class
})
public class LogMessageV2Type
    extends Message
{

    @XmlElement(name = "EventV2", required = true)
    protected List<EventV2> eventV2;

    /**
     * Gets the value of the eventV2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventV2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventV2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventV2 }
     * 
     * 
     */
    public List<EventV2> getEventV2() {
        if (eventV2 == null) {
            eventV2 = new ArrayList<EventV2>();
        }
        return this.eventV2;
    }

}
