//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.co.networkrail.xml.ns._2008.train.TrainActivationMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainCancellationMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainChangeIdentityMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainChangeLocationMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainChangeOriginMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainMovementMsgV1;
import uk.co.networkrail.xml.ns._2008.train.TrainReinstatementMsgV1;
import uk.co.networkrail.xml.ns._2008.train.UnidentifiedTrainMovementMsgV1;


/**
 * The root type for all XML messages.
 * 
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Addressee" type="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor" minOccurs="0"/>
 *         &lt;element name="Publication" type="{http://xml.networkrail.co.uk/ns/2008/EAI}Publication" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classification" type="{http://xml.networkrail.co.uk/ns/2008/EAI}PrivacyClassification" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="owner">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Network Rail"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="originMsgId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://xml.networkrail.co.uk/ns/2008/EAI}rfc2822id">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "sender",
    "addressee",
    "publication"
})
@XmlSeeAlso({
    HeartBeatMessage.class,
    ReplyMessageV2 .class,
    TrainActivationMsgV1 .class,
    TrainChangeLocationMsgV1 .class,
    TrainChangeIdentityMsgV1 .class,
    TrainCancellationMsgV1 .class,
    TrainMovementMsgV1 .class,
    UnidentifiedTrainMovementMsgV1 .class,
    TrainReinstatementMsgV1 .class,
    TrainChangeOriginMsgV1 .class,
    LogMessageV2Type.class,
    GeneralMsgV1 .class,
    DeadMessageV2Type.class
})
public class Message {

    @XmlElement(name = "Sender", required = true)
    protected Message.Sender sender;
    @XmlElement(name = "Addressee")
    protected MsgActor addressee;
    @XmlElement(name = "Publication")
    protected Publication publication;
    @XmlAttribute(name = "classification")
    protected PrivacyClassification classification;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "owner")
    protected String owner;
    @XmlAttribute(name = "originMsgId")
    protected String originMsgId;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link Message.Sender }
     *     
     */
    public Message.Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message.Sender }
     *     
     */
    public void setSender(Message.Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the addressee property.
     * 
     * @return
     *     possible object is
     *     {@link MsgActor }
     *     
     */
    public MsgActor getAddressee() {
        return addressee;
    }

    /**
     * Sets the value of the addressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgActor }
     *     
     */
    public void setAddressee(MsgActor value) {
        this.addressee = value;
    }

    /**
     * Gets the value of the publication property.
     * 
     * @return
     *     possible object is
     *     {@link Publication }
     *     
     */
    public Publication getPublication() {
        return publication;
    }

    /**
     * Sets the value of the publication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publication }
     *     
     */
    public void setPublication(Publication value) {
        this.publication = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyClassification }
     *     
     */
    public PrivacyClassification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyClassification }
     *     
     */
    public void setClassification(PrivacyClassification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the originMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginMsgId() {
        return originMsgId;
    }

    /**
     * Sets the value of the originMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginMsgId(String value) {
        this.originMsgId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Sender
        extends MsgActor
    {


    }

}
