//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.networkrail.xml.ns._2008.eai package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HeartBeatMsg_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/EAI", "HeartBeatMsg");
    private final static QName _WSRequestToken_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/EAI", "WSRequestToken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.networkrail.xml.ns._2008.eai
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link WSRequestToken }
     * 
     */
    public WSRequestToken createWSRequestToken() {
        return new WSRequestToken();
    }

    /**
     * Create an instance of {@link DeadMessageV2 }
     * 
     */
    public DeadMessageV2 createDeadMessageV2() {
        return new DeadMessageV2();
    }

    /**
     * Create an instance of {@link DeadMessageV2Type }
     * 
     */
    public DeadMessageV2Type createDeadMessageV2Type() {
        return new DeadMessageV2Type();
    }

    /**
     * Create an instance of {@link Message.Sender }
     * 
     */
    public Message.Sender createMessageSender() {
        return new Message.Sender();
    }

    /**
     * Create an instance of {@link MsgActor }
     * 
     */
    public MsgActor createMsgActor() {
        return new MsgActor();
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link EventV2 }
     * 
     */
    public EventV2 createEventV2() {
        return new EventV2();
    }

    /**
     * Create an instance of {@link ShortDescriptionType }
     * 
     */
    public ShortDescriptionType createShortDescriptionType() {
        return new ShortDescriptionType();
    }

    /**
     * Create an instance of {@link GeneralMsgV1 }
     * 
     */
    public GeneralMsgV1 createGeneralMsgV1() {
        return new GeneralMsgV1();
    }

    /**
     * Create an instance of {@link GeneralMsg }
     * 
     */
    public GeneralMsg createGeneralMsg() {
        return new GeneralMsg();
    }

    /**
     * Create an instance of {@link MsgAttribute }
     * 
     */
    public MsgAttribute createMsgAttribute() {
        return new MsgAttribute();
    }

    /**
     * Create an instance of {@link HeartBeatMessage }
     * 
     */
    public HeartBeatMessage createHeartBeatMessage() {
        return new HeartBeatMessage();
    }

    /**
     * Create an instance of {@link LogMessageV2 }
     * 
     */
    public LogMessageV2 createLogMessageV2() {
        return new LogMessageV2();
    }

    /**
     * Create an instance of {@link LogMessageV2Type }
     * 
     */
    public LogMessageV2Type createLogMessageV2Type() {
        return new LogMessageV2Type();
    }

    /**
     * Create an instance of {@link LongDescriptionType }
     * 
     */
    public LongDescriptionType createLongDescriptionType() {
        return new LongDescriptionType();
    }

    /**
     * Create an instance of {@link ReplyMessageV2 }
     * 
     */
    public ReplyMessageV2 createReplyMessageV2() {
        return new ReplyMessageV2();
    }

    /**
     * Create an instance of {@link UserToken }
     * 
     */
    public UserToken createUserToken() {
        return new UserToken();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeartBeatMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/EAI", name = "HeartBeatMsg")
    public JAXBElement<HeartBeatMessage> createHeartBeatMsg(HeartBeatMessage value) {
        return new JAXBElement<HeartBeatMessage>(_HeartBeatMsg_QNAME, HeartBeatMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSRequestToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/EAI", name = "WSRequestToken")
    public JAXBElement<WSRequestToken> createWSRequestToken(WSRequestToken value) {
        return new JAXBElement<WSRequestToken>(_WSRequestToken_QNAME, WSRequestToken.class, null, value);
    }

}
