//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A message sent in reply to another message.
 * 
 * <p>Java class for ReplyMessageV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReplyMessageV2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xml.networkrail.co.uk/ns/2008/EAI}Message">
 *       &lt;sequence>
 *         &lt;element name="Requestor" type="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor" minOccurs="0"/>
 *         &lt;element name="Event" type="{http://xml.networkrail.co.uk/ns/2008/EAI}EventV2" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="requestMsgId" use="required" type="{http://xml.networkrail.co.uk/ns/2008/EAI}rfc2822id" />
 *       &lt;attribute name="requestTimestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="requestReceived" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplyMessageV2", propOrder = {
    "requestor",
    "event"
})
public class ReplyMessageV2
    extends Message
{

    @XmlElement(name = "Requestor")
    protected MsgActor requestor;
    @XmlElement(name = "Event")
    protected List<EventV2> event;
    @XmlAttribute(name = "requestMsgId", required = true)
    protected String requestMsgId;
    @XmlAttribute(name = "requestTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestTimestamp;
    @XmlAttribute(name = "requestReceived")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestReceived;

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link MsgActor }
     *     
     */
    public MsgActor getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgActor }
     *     
     */
    public void setRequestor(MsgActor value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventV2 }
     * 
     * 
     */
    public List<EventV2> getEvent() {
        if (event == null) {
            event = new ArrayList<EventV2>();
        }
        return this.event;
    }

    /**
     * Gets the value of the requestMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMsgId() {
        return requestMsgId;
    }

    /**
     * Sets the value of the requestMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMsgId(String value) {
        this.requestMsgId = value;
    }

    /**
     * Gets the value of the requestTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestTimestamp() {
        return requestTimestamp;
    }

    /**
     * Sets the value of the requestTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestTimestamp(XMLGregorianCalendar value) {
        this.requestTimestamp = value;
    }

    /**
     * Gets the value of the requestReceived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestReceived() {
        return requestReceived;
    }

    /**
     * Sets the value of the requestReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestReceived(XMLGregorianCalendar value) {
        this.requestReceived = value;
    }

}
