//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.eai;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This is the user details passed to web service requrest to authenticate the user
 * 
 * <p>Java class for UserToken complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserToken">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authenicated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="User" type="{http://xml.networkrail.co.uk/ns/2008/EAI}MsgActor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserToken", propOrder = {
    "authenicated",
    "user"
})
public class UserToken {

    protected boolean authenicated;
    @XmlElement(name = "User", required = true)
    protected MsgActor user;

    /**
     * Gets the value of the authenicated property.
     * 
     */
    public boolean isAuthenicated() {
        return authenicated;
    }

    /**
     * Sets the value of the authenicated property.
     * 
     */
    public void setAuthenicated(boolean value) {
        this.authenicated = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link MsgActor }
     *     
     */
    public MsgActor getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgActor }
     *     
     */
    public void setUser(MsgActor value) {
        this.user = value;
    }

}
