//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATOCCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ATOCCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AM"/>
 *     &lt;enumeration value="AN"/>
 *     &lt;enumeration value="AR"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="CX"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="GW"/>
 *     &lt;enumeration value="GX"/>
 *     &lt;enumeration value="HT"/>
 *     &lt;enumeration value="HX"/>
 *     &lt;enumeration value="IL"/>
 *     &lt;enumeration value="ME"/>
 *     &lt;enumeration value="ML"/>
 *     &lt;enumeration value="NW"/>
 *     &lt;enumeration value="SN"/>
 *     &lt;enumeration value="SR"/>
 *     &lt;enumeration value="SS"/>
 *     &lt;enumeration value="SW"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TT"/>
 *     &lt;enumeration value="VL"/>
 *     &lt;enumeration value="VT"/>
 *     &lt;enumeration value="WB"/>
 *     &lt;enumeration value="WE"/>
 *     &lt;enumeration value="WN"/>
 *     &lt;enumeration value="WR"/>
 *     &lt;enumeration value="WW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ATOCCode")
@XmlEnum
public enum ATOCCode {

    AM,
    AN,
    AR,
    CC,
    CH,
    CT,
    CX,
    ES,
    GE,
    GR,
    GW,
    GX,
    HT,
    HX,
    IL,
    ME,
    ML,
    NW,
    SN,
    SR,
    SS,
    SW,
    TL,
    TT,
    VL,
    VT,
    WB,
    WE,
    WN,
    WR,
    WW;

    public String value() {
        return name();
    }

    public static ATOCCode fromValue(String v) {
        return valueOf(v);
    }

}
