//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CancellationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ON CALL"/>
 *     &lt;enumeration value="OUT OF PLAN"/>
 *     &lt;enumeration value="AT ORIGIN"/>
 *     &lt;enumeration value="EN ROUTE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CancellationType")
@XmlEnum
public enum CancellationType {

    @XmlEnumValue("ON CALL")
    ON_CALL("ON CALL"),
    @XmlEnumValue("OUT OF PLAN")
    OUT_OF_PLAN("OUT OF PLAN"),
    @XmlEnumValue("AT ORIGIN")
    AT_ORIGIN("AT ORIGIN"),
    @XmlEnumValue("EN ROUTE")
    EN_ROUTE("EN ROUTE");
    private final String value;

    CancellationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CancellationType fromValue(String v) {
        for (CancellationType c: CancellationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
