//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DelayAlertReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DelayAlertReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EXPLAINED"/>
 *     &lt;enumeration value="UNEXPLAINED"/>
 *     &lt;enumeration value="FTS"/>
 *     &lt;enumeration value="CANCELLATION"/>
 *     &lt;enumeration value="COO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DelayAlertReasonType")
@XmlEnum
public enum DelayAlertReasonType {

    EXPLAINED,
    UNEXPLAINED,
    FTS,
    CANCELLATION,
    COO;

    public String value() {
        return name();
    }

    public static DelayAlertReasonType fromValue(String v) {
        return valueOf(v);
    }

}
