//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Composite type used in delay attribution structures
 * 
 * <p>Java class for DelayHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelayHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DAUpdateType" type="{http://xml.networkrail.co.uk/ns/2008/Train}TRUSTDAUpdateTypeType"/>
 *         &lt;element name="Sequence" type="{http://xml.networkrail.co.uk/ns/2008/Train}TRUSTSequenceType" minOccurs="0"/>
 *         &lt;element name="SiteID" type="{http://xml.networkrail.co.uk/ns/2008/Train}TRUSTSiteIDType"/>
 *         &lt;element name="NCI" type="{http://xml.networkrail.co.uk/ns/2008/Train}TRUSTNCIType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelayHeaderType", propOrder = {
    "daUpdateType",
    "sequence",
    "siteID",
    "nci"
})
public class DelayHeaderType {

    @XmlElement(name = "DAUpdateType", required = true)
    @XmlSchemaType(name = "string")
    protected TRUSTDAUpdateTypeType daUpdateType;
    @XmlElement(name = "Sequence")
    protected String sequence;
    @XmlElement(name = "SiteID", required = true)
    protected String siteID;
    @XmlElement(name = "NCI")
    protected String nci;

    /**
     * Gets the value of the daUpdateType property.
     * 
     * @return
     *     possible object is
     *     {@link TRUSTDAUpdateTypeType }
     *     
     */
    public TRUSTDAUpdateTypeType getDAUpdateType() {
        return daUpdateType;
    }

    /**
     * Sets the value of the daUpdateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRUSTDAUpdateTypeType }
     *     
     */
    public void setDAUpdateType(TRUSTDAUpdateTypeType value) {
        this.daUpdateType = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the siteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteID() {
        return siteID;
    }

    /**
     * Sets the value of the siteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteID(String value) {
        this.siteID = value;
    }

    /**
     * Gets the value of the nci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCI() {
        return nci;
    }

    /**
     * Sets the value of the nci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCI(String value) {
        this.nci = value;
    }

}
