//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.networkrail.xml.ns._2008.train package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttributionReason_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributionReason");
    private final static QName _IncidentDescription_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentDescription");
    private final static QName _RailtrackManagerCode_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "RailtrackManagerCode");
    private final static QName _AlertNumber_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AlertNumber");
    private final static QName _RolledUpFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "RolledUpFlag");
    private final static QName _ResponsibleTrain_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ResponsibleTrain");
    private final static QName _ScheduleStartTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ScheduleStartTimestamp");
    private final static QName _MovementType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "MovementType");
    private final static QName _IncidentID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentID");
    private final static QName _RevisedTrainID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "RevisedTrainID");
    private final static QName _AlertType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AlertType");
    private final static QName _AlertHeader_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AlertHeader");
    private final static QName _AttributionText_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributionText");
    private final static QName _NextLocationStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "NextLocationStanox");
    private final static QName _ResponsibleManager_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ResponsibleManager");
    private final static QName _Sector_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Sector");
    private final static QName _Zone_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Zone");
    private final static QName _MessageText_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "MessageText");
    private final static QName _UpdateType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "UpdateType");
    private final static QName _LocationStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "LocationStanox");
    private final static QName _AttributionStatus_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributionStatus");
    private final static QName _Location_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Location");
    private final static QName _PlannedDepartureTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "PlannedDepartureTimestamp");
    private final static QName _TrainCallMode_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainCallMode");
    private final static QName _WTTID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "WTTID");
    private final static QName _DelayXRef_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "DelayXRef");
    private final static QName _WTTTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "WTTTimestamp");
    private final static QName _ScheduleType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ScheduleType");
    private final static QName _LocationStanme_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "LocationStanme");
    private final static QName _ReasonDescription_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ReasonDescription");
    private final static QName _IncidentStatus_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentStatus");
    private final static QName _AutoExpectedFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AutoExpectedFlag");
    private final static QName _Delay_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Delay");
    private final static QName _EventInitiation_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EventInitiation");
    private final static QName _DelayAlertReason_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "DelayAlertReason");
    private final static QName _Attributed_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Attributed");
    private final static QName _TrainCancellationType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainCancellationType");
    private final static QName _OriginalWTTTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OriginalWTTTimestamp");
    private final static QName _Route_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Route");
    private final static QName _FaultSystem_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "FaultSystem");
    private final static QName _Unexplained_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Unexplained");
    private final static QName _IncidentCloseTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentCloseTimestamp");
    private final static QName _MessageQueueTime_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "MessageQueueTime");
    private final static QName _Unattributed_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Unattributed");
    private final static QName _ReasonCode_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ReasonCode");
    private final static QName _EventSource_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EventSource");
    private final static QName _Area_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Area");
    private final static QName _IncidentEndTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentEndTimestamp");
    private final static QName _EquipmentNumber_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EquipmentNumber");
    private final static QName _AttributionUpdateType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributionUpdateType");
    private final static QName _GBTTTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "GBTTTimestamp");
    private final static QName _AlertTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AlertTimestamp");
    private final static QName _FTS_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "FTS");
    private final static QName _Direction_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Direction");
    private final static QName _UIDNumber_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "UIDNumber");
    private final static QName _DelayMonitoringFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "DelayMonitoringFlag");
    private final static QName _IncidentAttributionStatus_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentAttributionStatus");
    private final static QName _NetworkDelayFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "NetworkDelayFlag");
    private final static QName _OriginStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OriginStanox");
    private final static QName _TrainPlanOrigin_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainPlanOrigin");
    private final static QName _DelayLongDecription_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "DelayLongDecription");
    private final static QName _TerminatedFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TerminatedFlag");
    private final static QName _Division_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Division");
    private final static QName _TOPSUID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TOPSUID");
    private final static QName _OffRouteFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OffRouteFlag");
    private final static QName _FaultNumber_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "FaultNumber");
    private final static QName _EndLocationStanme_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EndLocationStanme");
    private final static QName _ScheduledWTTID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ScheduledWTTID");
    private final static QName _AttributionSuccessFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributionSuccessFlag");
    private final static QName _OriginalTrainID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OriginalTrainID");
    private final static QName _AttributedFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "AttributedFlag");
    private final static QName _BRSCode_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "BRSCode");
    private final static QName _ScheduleEndTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ScheduleEndTimestamp");
    private final static QName _NextReportRunTime_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "NextReportRunTime");
    private final static QName _CurrentTrainID_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "CurrentTrainID");
    private final static QName _TimetableVariation_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TimetableVariation");
    private final static QName _VariationStatus_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "VariationStatus");
    private final static QName _FTSAttributedFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "FTSAttributedFlag");
    private final static QName _MergedIncident_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "MergedIncident");
    private final static QName _PlannedMovementType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "PlannedMovementType");
    private final static QName _ConfirmedFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ConfirmedFlag");
    private final static QName _SplitFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "SplitFlag");
    private final static QName _Platform_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Platform");
    private final static QName _OriginalLocationStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OriginalLocationStanox");
    private final static QName _ScheduleSource_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ScheduleSource");
    private final static QName _ReportingLocationStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "ReportingLocationStanox");
    private final static QName _TrainFileAddress_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainFileAddress");
    private final static QName _TrainCallType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainCallType");
    private final static QName _IncidentType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentType");
    private final static QName _StationCrossReference_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "StationCrossReference");
    private final static QName _CancellationType_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "CancellationType");
    private final static QName _TrainServiceCode_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainServiceCode");
    private final static QName _TOC_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TOC");
    private final static QName _EndLocationStanox_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EndLocationStanox");
    private final static QName _Line_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "Line");
    private final static QName _TrainPlanOriginTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "TrainPlanOriginTimestamp");
    private final static QName _EventTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "EventTimestamp");
    private final static QName _NCI_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "NCI");
    private final static QName _RevisionFlag_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "RevisionFlag");
    private final static QName _DepartureTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "DepartureTimestamp");
    private final static QName _OriginalAlertNumber_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "OriginalAlertNumber");
    private final static QName _IncidentTimestamp_QNAME = new QName("http://xml.networkrail.co.uk/ns/2008/Train", "IncidentTimestamp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.networkrail.xml.ns._2008.train
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScheduleLocationV2 }
     * 
     */
    public ScheduleLocationV2 createScheduleLocationV2() {
        return new ScheduleLocationV2();
    }

    /**
     * Create an instance of {@link TrainChangeOriginMsgV1 }
     * 
     */
    public TrainChangeOriginMsgV1 createTrainChangeOriginMsgV1() {
        return new TrainChangeOriginMsgV1();
    }

    /**
     * Create an instance of {@link TrainChangeOriginData }
     * 
     */
    public TrainChangeOriginData createTrainChangeOriginData() {
        return new TrainChangeOriginData();
    }

    /**
     * Create an instance of {@link TrainCancellationData }
     * 
     */
    public TrainCancellationData createTrainCancellationData() {
        return new TrainCancellationData();
    }

    /**
     * Create an instance of {@link TrainReinstatementMsgV1 }
     * 
     */
    public TrainReinstatementMsgV1 createTrainReinstatementMsgV1() {
        return new TrainReinstatementMsgV1();
    }

    /**
     * Create an instance of {@link TrainReinstatementData }
     * 
     */
    public TrainReinstatementData createTrainReinstatementData() {
        return new TrainReinstatementData();
    }

    /**
     * Create an instance of {@link UnidentifiedTrainMovementMsgV1 }
     * 
     */
    public UnidentifiedTrainMovementMsgV1 createUnidentifiedTrainMovementMsgV1() {
        return new UnidentifiedTrainMovementMsgV1();
    }

    /**
     * Create an instance of {@link UnidentifiedTrainMovementData }
     * 
     */
    public UnidentifiedTrainMovementData createUnidentifiedTrainMovementData() {
        return new UnidentifiedTrainMovementData();
    }

    /**
     * Create an instance of {@link OperatorData }
     * 
     */
    public OperatorData createOperatorData() {
        return new OperatorData();
    }

    /**
     * Create an instance of {@link AttributionStatusData }
     * 
     */
    public AttributionStatusData createAttributionStatusData() {
        return new AttributionStatusData();
    }

    /**
     * Create an instance of {@link TrainMovementMsgV1 }
     * 
     */
    public TrainMovementMsgV1 createTrainMovementMsgV1() {
        return new TrainMovementMsgV1();
    }

    /**
     * Create an instance of {@link TrainMovementData }
     * 
     */
    public TrainMovementData createTrainMovementData() {
        return new TrainMovementData();
    }

    /**
     * Create an instance of {@link TrainCancellationMsgV1 }
     * 
     */
    public TrainCancellationMsgV1 createTrainCancellationMsgV1() {
        return new TrainCancellationMsgV1();
    }

    /**
     * Create an instance of {@link TrainDelayAlertData }
     * 
     */
    public TrainDelayAlertData createTrainDelayAlertData() {
        return new TrainDelayAlertData();
    }

    /**
     * Create an instance of {@link TrainChangeLocationData }
     * 
     */
    public TrainChangeLocationData createTrainChangeLocationData() {
        return new TrainChangeLocationData();
    }

    /**
     * Create an instance of {@link TrainChangeIdentityMsgV1 }
     * 
     */
    public TrainChangeIdentityMsgV1 createTrainChangeIdentityMsgV1() {
        return new TrainChangeIdentityMsgV1();
    }

    /**
     * Create an instance of {@link TrainChangeIdentityData }
     * 
     */
    public TrainChangeIdentityData createTrainChangeIdentityData() {
        return new TrainChangeIdentityData();
    }

    /**
     * Create an instance of {@link TrainChangeLocationMsgV1 }
     * 
     */
    public TrainChangeLocationMsgV1 createTrainChangeLocationMsgV1() {
        return new TrainChangeLocationMsgV1();
    }

    /**
     * Create an instance of {@link TrainActivationData }
     * 
     */
    public TrainActivationData createTrainActivationData() {
        return new TrainActivationData();
    }

    /**
     * Create an instance of {@link TrainActivationMsgV1 }
     * 
     */
    public TrainActivationMsgV1 createTrainActivationMsgV1() {
        return new TrainActivationMsgV1();
    }

    /**
     * Create an instance of {@link AlertHeaderType }
     * 
     */
    public AlertHeaderType createAlertHeaderType() {
        return new AlertHeaderType();
    }

    /**
     * Create an instance of {@link DelayAttributionData }
     * 
     */
    public DelayAttributionData createDelayAttributionData() {
        return new DelayAttributionData();
    }

    /**
     * Create an instance of {@link DelayHeaderType }
     * 
     */
    public DelayHeaderType createDelayHeaderType() {
        return new DelayHeaderType();
    }

    /**
     * Create an instance of {@link LocationTimes }
     * 
     */
    public LocationTimes createLocationTimes() {
        return new LocationTimes();
    }

    /**
     * Create an instance of {@link TrainID }
     * 
     */
    public TrainID createTrainID() {
        return new TrainID();
    }

    /**
     * Create an instance of {@link ScheduleSegment }
     * 
     */
    public ScheduleSegment createScheduleSegment() {
        return new ScheduleSegment();
    }

    /**
     * Create an instance of {@link ScheduleLocationV2 .Pass }
     * 
     */
    public ScheduleLocationV2 .Pass createScheduleLocationV2Pass() {
        return new ScheduleLocationV2 .Pass();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelayAlertReasonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributionReason")
    public JAXBElement<DelayAlertReasonType> createAttributionReason(DelayAlertReasonType value) {
        return new JAXBElement<DelayAlertReasonType>(_AttributionReason_QNAME, DelayAlertReasonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentDescription")
    public JAXBElement<String> createIncidentDescription(String value) {
        return new JAXBElement<String>(_IncidentDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "RailtrackManagerCode")
    public JAXBElement<String> createRailtrackManagerCode(String value) {
        return new JAXBElement<String>(_RailtrackManagerCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AlertNumber")
    public JAXBElement<BigInteger> createAlertNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_AlertNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "RolledUpFlag")
    public JAXBElement<Boolean> createRolledUpFlag(Boolean value) {
        return new JAXBElement<Boolean>(_RolledUpFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ResponsibleTrain")
    public JAXBElement<String> createResponsibleTrain(String value) {
        return new JAXBElement<String>(_ResponsibleTrain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ScheduleStartTimestamp")
    public JAXBElement<XMLGregorianCalendar> createScheduleStartTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ScheduleStartTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrainMovementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "MovementType")
    public JAXBElement<TrainMovementType> createMovementType(TrainMovementType value) {
        return new JAXBElement<TrainMovementType>(_MovementType_QNAME, TrainMovementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentID")
    public JAXBElement<String> createIncidentID(String value) {
        return new JAXBElement<String>(_IncidentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "RevisedTrainID")
    public JAXBElement<String> createRevisedTrainID(String value) {
        return new JAXBElement<String>(_RevisedTrainID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlertType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AlertType")
    public JAXBElement<AlertType> createAlertType(AlertType value) {
        return new JAXBElement<AlertType>(_AlertType_QNAME, AlertType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlertHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AlertHeader")
    public JAXBElement<AlertHeaderType> createAlertHeader(AlertHeaderType value) {
        return new JAXBElement<AlertHeaderType>(_AlertHeader_QNAME, AlertHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributionText")
    public JAXBElement<String> createAttributionText(String value) {
        return new JAXBElement<String>(_AttributionText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "NextLocationStanox")
    public JAXBElement<String> createNextLocationStanox(String value) {
        return new JAXBElement<String>(_NextLocationStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ResponsibleManager")
    public JAXBElement<String> createResponsibleManager(String value) {
        return new JAXBElement<String>(_ResponsibleManager_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Sector")
    public JAXBElement<Integer> createSector(Integer value) {
        return new JAXBElement<Integer>(_Sector_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Zone")
    public JAXBElement<String> createZone(String value) {
        return new JAXBElement<String>(_Zone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "MessageText")
    public JAXBElement<String> createMessageText(String value) {
        return new JAXBElement<String>(_MessageText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "UpdateType")
    public JAXBElement<String> createUpdateType(String value) {
        return new JAXBElement<String>(_UpdateType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "LocationStanox")
    public JAXBElement<String> createLocationStanox(String value) {
        return new JAXBElement<String>(_LocationStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributionStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributionStatus")
    public JAXBElement<AttributionStatusType> createAttributionStatus(AttributionStatusType value) {
        return new JAXBElement<AttributionStatusType>(_AttributionStatus_QNAME, AttributionStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "PlannedDepartureTimestamp")
    public JAXBElement<XMLGregorianCalendar> createPlannedDepartureTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlannedDepartureTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainCallMode")
    public JAXBElement<String> createTrainCallMode(String value) {
        return new JAXBElement<String>(_TrainCallMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "WTTID")
    public JAXBElement<String> createWTTID(String value) {
        return new JAXBElement<String>(_WTTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "DelayXRef")
    public JAXBElement<String> createDelayXRef(String value) {
        return new JAXBElement<String>(_DelayXRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "WTTTimestamp")
    public JAXBElement<XMLGregorianCalendar> createWTTTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_WTTTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ScheduleType")
    public JAXBElement<ScheduleType> createScheduleType(ScheduleType value) {
        return new JAXBElement<ScheduleType>(_ScheduleType_QNAME, ScheduleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "LocationStanme")
    public JAXBElement<String> createLocationStanme(String value) {
        return new JAXBElement<String>(_LocationStanme_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ReasonDescription")
    public JAXBElement<String> createReasonDescription(String value) {
        return new JAXBElement<String>(_ReasonDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncidentStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentStatus")
    public JAXBElement<IncidentStatusType> createIncidentStatus(IncidentStatusType value) {
        return new JAXBElement<IncidentStatusType>(_IncidentStatus_QNAME, IncidentStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AutoExpectedFlag")
    public JAXBElement<Boolean> createAutoExpectedFlag(Boolean value) {
        return new JAXBElement<Boolean>(_AutoExpectedFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Delay")
    public JAXBElement<BigInteger> createDelay(BigInteger value) {
        return new JAXBElement<BigInteger>(_Delay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventInitiationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EventInitiation")
    public JAXBElement<EventInitiationType> createEventInitiation(EventInitiationType value) {
        return new JAXBElement<EventInitiationType>(_EventInitiation_QNAME, EventInitiationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelayAlertReasonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "DelayAlertReason")
    public JAXBElement<DelayAlertReasonType> createDelayAlertReason(DelayAlertReasonType value) {
        return new JAXBElement<DelayAlertReasonType>(_DelayAlertReason_QNAME, DelayAlertReasonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Attributed")
    public JAXBElement<BigInteger> createAttributed(BigInteger value) {
        return new JAXBElement<BigInteger>(_Attributed_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancellationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainCancellationType")
    public JAXBElement<CancellationType> createTrainCancellationType(CancellationType value) {
        return new JAXBElement<CancellationType>(_TrainCancellationType_QNAME, CancellationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OriginalWTTTimestamp")
    public JAXBElement<XMLGregorianCalendar> createOriginalWTTTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OriginalWTTTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Route")
    public JAXBElement<String> createRoute(String value) {
        return new JAXBElement<String>(_Route_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "FaultSystem")
    public JAXBElement<String> createFaultSystem(String value) {
        return new JAXBElement<String>(_FaultSystem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Unexplained")
    public JAXBElement<BigInteger> createUnexplained(BigInteger value) {
        return new JAXBElement<BigInteger>(_Unexplained_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentCloseTimestamp")
    public JAXBElement<XMLGregorianCalendar> createIncidentCloseTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IncidentCloseTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "MessageQueueTime")
    public JAXBElement<XMLGregorianCalendar> createMessageQueueTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MessageQueueTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Unattributed")
    public JAXBElement<BigInteger> createUnattributed(BigInteger value) {
        return new JAXBElement<BigInteger>(_Unattributed_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ReasonCode")
    public JAXBElement<String> createReasonCode(String value) {
        return new JAXBElement<String>(_ReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventSourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EventSource")
    public JAXBElement<EventSourceType> createEventSource(EventSourceType value) {
        return new JAXBElement<EventSourceType>(_EventSource_QNAME, EventSourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Area")
    public JAXBElement<String> createArea(String value) {
        return new JAXBElement<String>(_Area_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentEndTimestamp")
    public JAXBElement<XMLGregorianCalendar> createIncidentEndTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IncidentEndTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EquipmentNumber")
    public JAXBElement<String> createEquipmentNumber(String value) {
        return new JAXBElement<String>(_EquipmentNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributionUpdateType")
    public JAXBElement<UpdateType> createAttributionUpdateType(UpdateType value) {
        return new JAXBElement<UpdateType>(_AttributionUpdateType_QNAME, UpdateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "GBTTTimestamp")
    public JAXBElement<XMLGregorianCalendar> createGBTTTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_GBTTTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AlertTimestamp")
    public JAXBElement<XMLGregorianCalendar> createAlertTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AlertTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "FTS")
    public JAXBElement<String> createFTS(String value) {
        return new JAXBElement<String>(_FTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Direction")
    public JAXBElement<DirectionType> createDirection(DirectionType value) {
        return new JAXBElement<DirectionType>(_Direction_QNAME, DirectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "UIDNumber")
    public JAXBElement<String> createUIDNumber(String value) {
        return new JAXBElement<String>(_UIDNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "DelayMonitoringFlag")
    public JAXBElement<Boolean> createDelayMonitoringFlag(Boolean value) {
        return new JAXBElement<Boolean>(_DelayMonitoringFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributionStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentAttributionStatus")
    public JAXBElement<AttributionStatusType> createIncidentAttributionStatus(AttributionStatusType value) {
        return new JAXBElement<AttributionStatusType>(_IncidentAttributionStatus_QNAME, AttributionStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "NetworkDelayFlag")
    public JAXBElement<Boolean> createNetworkDelayFlag(Boolean value) {
        return new JAXBElement<Boolean>(_NetworkDelayFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OriginStanox")
    public JAXBElement<String> createOriginStanox(String value) {
        return new JAXBElement<String>(_OriginStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainPlanOrigin")
    public JAXBElement<String> createTrainPlanOrigin(String value) {
        return new JAXBElement<String>(_TrainPlanOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "DelayLongDecription")
    public JAXBElement<String> createDelayLongDecription(String value) {
        return new JAXBElement<String>(_DelayLongDecription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TerminatedFlag")
    public JAXBElement<Boolean> createTerminatedFlag(Boolean value) {
        return new JAXBElement<Boolean>(_TerminatedFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Division")
    public JAXBElement<String> createDivision(String value) {
        return new JAXBElement<String>(_Division_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TOPSUID")
    public JAXBElement<String> createTOPSUID(String value) {
        return new JAXBElement<String>(_TOPSUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OffRouteFlag")
    public JAXBElement<Boolean> createOffRouteFlag(Boolean value) {
        return new JAXBElement<Boolean>(_OffRouteFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "FaultNumber")
    public JAXBElement<String> createFaultNumber(String value) {
        return new JAXBElement<String>(_FaultNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EndLocationStanme")
    public JAXBElement<String> createEndLocationStanme(String value) {
        return new JAXBElement<String>(_EndLocationStanme_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ScheduledWTTID")
    public JAXBElement<String> createScheduledWTTID(String value) {
        return new JAXBElement<String>(_ScheduledWTTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributionSuccessFlag")
    public JAXBElement<String> createAttributionSuccessFlag(String value) {
        return new JAXBElement<String>(_AttributionSuccessFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OriginalTrainID")
    public JAXBElement<String> createOriginalTrainID(String value) {
        return new JAXBElement<String>(_OriginalTrainID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "AttributedFlag")
    public JAXBElement<Boolean> createAttributedFlag(Boolean value) {
        return new JAXBElement<Boolean>(_AttributedFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "BRSCode")
    public JAXBElement<String> createBRSCode(String value) {
        return new JAXBElement<String>(_BRSCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ScheduleEndTimestamp")
    public JAXBElement<XMLGregorianCalendar> createScheduleEndTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ScheduleEndTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "NextReportRunTime")
    public JAXBElement<Integer> createNextReportRunTime(Integer value) {
        return new JAXBElement<Integer>(_NextReportRunTime_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "CurrentTrainID")
    public JAXBElement<String> createCurrentTrainID(String value) {
        return new JAXBElement<String>(_CurrentTrainID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TimetableVariation")
    public JAXBElement<Integer> createTimetableVariation(Integer value) {
        return new JAXBElement<Integer>(_TimetableVariation_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "VariationStatus")
    public JAXBElement<String> createVariationStatus(String value) {
        return new JAXBElement<String>(_VariationStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "FTSAttributedFlag")
    public JAXBElement<String> createFTSAttributedFlag(String value) {
        return new JAXBElement<String>(_FTSAttributedFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "MergedIncident")
    public JAXBElement<String> createMergedIncident(String value) {
        return new JAXBElement<String>(_MergedIncident_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrainMovementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "PlannedMovementType")
    public JAXBElement<TrainMovementType> createPlannedMovementType(TrainMovementType value) {
        return new JAXBElement<TrainMovementType>(_PlannedMovementType_QNAME, TrainMovementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ConfirmedFlag")
    public JAXBElement<Boolean> createConfirmedFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ConfirmedFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "SplitFlag")
    public JAXBElement<Boolean> createSplitFlag(Boolean value) {
        return new JAXBElement<Boolean>(_SplitFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Platform")
    public JAXBElement<String> createPlatform(String value) {
        return new JAXBElement<String>(_Platform_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OriginalLocationStanox")
    public JAXBElement<String> createOriginalLocationStanox(String value) {
        return new JAXBElement<String>(_OriginalLocationStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleSource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ScheduleSource")
    public JAXBElement<ScheduleSource> createScheduleSource(ScheduleSource value) {
        return new JAXBElement<ScheduleSource>(_ScheduleSource_QNAME, ScheduleSource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "ReportingLocationStanox")
    public JAXBElement<String> createReportingLocationStanox(String value) {
        return new JAXBElement<String>(_ReportingLocationStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainFileAddress")
    public JAXBElement<String> createTrainFileAddress(String value) {
        return new JAXBElement<String>(_TrainFileAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainCallType")
    public JAXBElement<String> createTrainCallType(String value) {
        return new JAXBElement<String>(_TrainCallType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentType")
    public JAXBElement<String> createIncidentType(String value) {
        return new JAXBElement<String>(_IncidentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "StationCrossReference")
    public JAXBElement<String> createStationCrossReference(String value) {
        return new JAXBElement<String>(_StationCrossReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "CancellationType")
    public JAXBElement<String> createCancellationType(String value) {
        return new JAXBElement<String>(_CancellationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainServiceCode")
    public JAXBElement<String> createTrainServiceCode(String value) {
        return new JAXBElement<String>(_TrainServiceCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TOC")
    public JAXBElement<String> createTOC(String value) {
        return new JAXBElement<String>(_TOC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EndLocationStanox")
    public JAXBElement<String> createEndLocationStanox(String value) {
        return new JAXBElement<String>(_EndLocationStanox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "Line")
    public JAXBElement<String> createLine(String value) {
        return new JAXBElement<String>(_Line_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "TrainPlanOriginTimestamp")
    public JAXBElement<XMLGregorianCalendar> createTrainPlanOriginTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TrainPlanOriginTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "EventTimestamp")
    public JAXBElement<XMLGregorianCalendar> createEventTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EventTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "NCI")
    public JAXBElement<String> createNCI(String value) {
        return new JAXBElement<String>(_NCI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "RevisionFlag")
    public JAXBElement<Boolean> createRevisionFlag(Boolean value) {
        return new JAXBElement<Boolean>(_RevisionFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "DepartureTimestamp")
    public JAXBElement<XMLGregorianCalendar> createDepartureTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartureTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "OriginalAlertNumber")
    public JAXBElement<BigInteger> createOriginalAlertNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_OriginalAlertNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", name = "IncidentTimestamp")
    public JAXBElement<XMLGregorianCalendar> createIncidentTimestamp(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IncidentTimestamp_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
