//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.networkrail.co.uk/ns/2008/Train", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.networkrail.xml.ns._2008.train;
