//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PowerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PowerType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="DEM"/>
 *     &lt;enumeration value="DMU"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="ED"/>
 *     &lt;enumeration value="EML"/>
 *     &lt;enumeration value="EMU"/>
 *     &lt;enumeration value="EPU"/>
 *     &lt;enumeration value="HST"/>
 *     &lt;enumeration value="LDS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PowerType")
@XmlEnum
public enum PowerType {

    D,
    DEM,
    DMU,
    E,
    ED,
    EML,
    EMU,
    EPU,
    HST,
    LDS;

    public String value() {
        return name();
    }

    public static PowerType fromValue(String v) {
        return valueOf(v);
    }

}
