//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Segment of train journey with constant header fields
 * 
 * <p>Java class for ScheduleSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScheduleSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="UnitClassRange" type="{http://xml.networkrail.co.uk/ns/2008/Train}UnitClassRange"/>
 *           &lt;element name="TrailingLoad">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://xml.networkrail.co.uk/ns/2008/NR}Kilogram">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="OpChar" type="{http://xml.networkrail.co.uk/ns/2008/Train}OpChar" maxOccurs="6" minOccurs="0"/>
 *         &lt;element name="Catering" type="{http://xml.networkrail.co.uk/ns/2008/Train}Catering" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="ScheduleLocationV2" type="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduleLocationV2" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="trainCategory" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="2"/>
 *             &lt;enumeration value="XC"/>
 *             &lt;enumeration value="XD"/>
 *             &lt;enumeration value="XH"/>
 *             &lt;enumeration value="XI"/>
 *             &lt;enumeration value="XJ"/>
 *             &lt;enumeration value="XM"/>
 *             &lt;enumeration value="XR"/>
 *             &lt;enumeration value="XU"/>
 *             &lt;enumeration value="XZ"/>
 *             &lt;enumeration value="OH"/>
 *             &lt;enumeration value="OL"/>
 *             &lt;enumeration value="OM"/>
 *             &lt;enumeration value="OS"/>
 *             &lt;enumeration value="OU"/>
 *             &lt;enumeration value="OW"/>
 *             &lt;enumeration value="PP"/>
 *             &lt;enumeration value="PM"/>
 *             &lt;enumeration value="PJ"/>
 *             &lt;enumeration value="PE"/>
 *             &lt;enumeration value="PH"/>
 *             &lt;enumeration value="PL"/>
 *             &lt;enumeration value="PS"/>
 *             &lt;enumeration value="PV"/>
 *             &lt;enumeration value="H2"/>
 *             &lt;enumeration value="J2"/>
 *             &lt;enumeration value="J3"/>
 *             &lt;enumeration value="J4"/>
 *             &lt;enumeration value="J5"/>
 *             &lt;enumeration value="J6"/>
 *             &lt;enumeration value="H8"/>
 *             &lt;enumeration value="J8"/>
 *             &lt;enumeration value="H9"/>
 *             &lt;enumeration value="J9"/>
 *             &lt;enumeration value="H0"/>
 *             &lt;enumeration value="H1"/>
 *             &lt;enumeration value="H3"/>
 *             &lt;enumeration value="H4"/>
 *             &lt;enumeration value="H5"/>
 *             &lt;enumeration value="H6"/>
 *             &lt;enumeration value="A0"/>
 *             &lt;enumeration value="B0"/>
 *             &lt;enumeration value="E0"/>
 *             &lt;enumeration value="B1"/>
 *             &lt;enumeration value="B4"/>
 *             &lt;enumeration value="B5"/>
 *             &lt;enumeration value="B6"/>
 *             &lt;enumeration value="B7"/>
 *             &lt;enumeration value="DC"/>
 *             &lt;enumeration value="DD"/>
 *             &lt;enumeration value="DL"/>
 *             &lt;enumeration value="DO"/>
 *             &lt;enumeration value="DP"/>
 *             &lt;enumeration value="FF"/>
 *             &lt;enumeration value="GG"/>
 *             &lt;enumeration value="PES"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="trainIdentity" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://xml.networkrail.co.uk/ns/2008/Train}TrainIdentity">
 *             &lt;maxLength value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="trainServiceCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://xml.networkrail.co.uk/ns/2008/Train}TrainServiceCode">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="powerType" use="required" type="{http://xml.networkrail.co.uk/ns/2008/Train}PowerType" />
 *       &lt;attribute name="UICCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://xml.networkrail.co.uk/ns/2008/Train}UICCode">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="routeCode" type="{http://xml.networkrail.co.uk/ns/2008/Train}RouteCodeV2" />
 *       &lt;attribute name="businessSector" type="{http://xml.networkrail.co.uk/ns/2008/Train}BusinessSector" />
 *       &lt;attribute name="speed" type="{http://xml.networkrail.co.uk/ns/2008/NR}mph" />
 *       &lt;attribute name="seatingClass" type="{http://xml.networkrail.co.uk/ns/2008/Train}SeatingClass" />
 *       &lt;attribute name="sleepers" type="{http://xml.networkrail.co.uk/ns/2008/Train}Sleepers" />
 *       &lt;attribute name="reservations" type="{http://xml.networkrail.co.uk/ns/2008/Train}Reservations" />
 *       &lt;attribute name="serviceBrand" type="{http://xml.networkrail.co.uk/ns/2008/Train}ServiceBrand" />
 *       &lt;attribute name="ATOCCode" type="{http://xml.networkrail.co.uk/ns/2008/Train}ATOCCode" />
 *       &lt;attribute name="TOPSCategory">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="profitCentre">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="8"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sector">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="subSector">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="tractionClass">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="4"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleSegment", propOrder = {
    "unitClassRange",
    "trailingLoad",
    "opChar",
    "catering",
    "scheduleLocationV2"
})
public class ScheduleSegment {

    @XmlElement(name = "UnitClassRange")
    @XmlSchemaType(name = "string")
    protected UnitClassRange unitClassRange;
    @XmlElement(name = "TrailingLoad")
    protected BigInteger trailingLoad;
    @XmlElement(name = "OpChar")
    @XmlSchemaType(name = "string")
    protected List<OpChar> opChar;
    @XmlElement(name = "Catering")
    @XmlSchemaType(name = "string")
    protected List<Catering> catering;
    @XmlElement(name = "ScheduleLocationV2", required = true)
    protected List<ScheduleLocationV2> scheduleLocationV2;
    @XmlAttribute(name = "trainCategory", required = true)
    protected String trainCategory;
    @XmlAttribute(name = "trainIdentity", required = true)
    protected String trainIdentity;
    @XmlAttribute(name = "trainServiceCode", required = true)
    protected String trainServiceCode;
    @XmlAttribute(name = "powerType", required = true)
    protected PowerType powerType;
    @XmlAttribute(name = "UICCode")
    protected String uicCode;
    @XmlAttribute(name = "routeCode")
    protected String routeCode;
    @XmlAttribute(name = "businessSector")
    protected String businessSector;
    @XmlAttribute(name = "speed")
    protected BigInteger speed;
    @XmlAttribute(name = "seatingClass")
    protected SeatingClass seatingClass;
    @XmlAttribute(name = "sleepers")
    protected Sleepers sleepers;
    @XmlAttribute(name = "reservations")
    protected String reservations;
    @XmlAttribute(name = "serviceBrand")
    protected String serviceBrand;
    @XmlAttribute(name = "ATOCCode")
    protected ATOCCode atocCode;
    @XmlAttribute(name = "TOPSCategory")
    protected String topsCategory;
    @XmlAttribute(name = "profitCentre")
    protected String profitCentre;
    @XmlAttribute(name = "sector")
    protected String sector;
    @XmlAttribute(name = "subSector")
    protected String subSector;
    @XmlAttribute(name = "tractionClass")
    protected String tractionClass;

    /**
     * Gets the value of the unitClassRange property.
     * 
     * @return
     *     possible object is
     *     {@link UnitClassRange }
     *     
     */
    public UnitClassRange getUnitClassRange() {
        return unitClassRange;
    }

    /**
     * Sets the value of the unitClassRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitClassRange }
     *     
     */
    public void setUnitClassRange(UnitClassRange value) {
        this.unitClassRange = value;
    }

    /**
     * Gets the value of the trailingLoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrailingLoad() {
        return trailingLoad;
    }

    /**
     * Sets the value of the trailingLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrailingLoad(BigInteger value) {
        this.trailingLoad = value;
    }

    /**
     * Gets the value of the opChar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opChar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpChar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpChar }
     * 
     * 
     */
    public List<OpChar> getOpChar() {
        if (opChar == null) {
            opChar = new ArrayList<OpChar>();
        }
        return this.opChar;
    }

    /**
     * Gets the value of the catering property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catering property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatering().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Catering }
     * 
     * 
     */
    public List<Catering> getCatering() {
        if (catering == null) {
            catering = new ArrayList<Catering>();
        }
        return this.catering;
    }

    /**
     * Gets the value of the scheduleLocationV2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduleLocationV2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduleLocationV2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduleLocationV2 }
     * 
     * 
     */
    public List<ScheduleLocationV2> getScheduleLocationV2() {
        if (scheduleLocationV2 == null) {
            scheduleLocationV2 = new ArrayList<ScheduleLocationV2>();
        }
        return this.scheduleLocationV2;
    }

    /**
     * Gets the value of the trainCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainCategory() {
        return trainCategory;
    }

    /**
     * Sets the value of the trainCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainCategory(String value) {
        this.trainCategory = value;
    }

    /**
     * Gets the value of the trainIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainIdentity() {
        return trainIdentity;
    }

    /**
     * Sets the value of the trainIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainIdentity(String value) {
        this.trainIdentity = value;
    }

    /**
     * Gets the value of the trainServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainServiceCode() {
        return trainServiceCode;
    }

    /**
     * Sets the value of the trainServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainServiceCode(String value) {
        this.trainServiceCode = value;
    }

    /**
     * Gets the value of the powerType property.
     * 
     * @return
     *     possible object is
     *     {@link PowerType }
     *     
     */
    public PowerType getPowerType() {
        return powerType;
    }

    /**
     * Sets the value of the powerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerType }
     *     
     */
    public void setPowerType(PowerType value) {
        this.powerType = value;
    }

    /**
     * Gets the value of the uicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUICCode() {
        return uicCode;
    }

    /**
     * Sets the value of the uicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUICCode(String value) {
        this.uicCode = value;
    }

    /**
     * Gets the value of the routeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteCode() {
        return routeCode;
    }

    /**
     * Sets the value of the routeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteCode(String value) {
        this.routeCode = value;
    }

    /**
     * Gets the value of the businessSector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessSector() {
        return businessSector;
    }

    /**
     * Sets the value of the businessSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessSector(String value) {
        this.businessSector = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpeed(BigInteger value) {
        this.speed = value;
    }

    /**
     * Gets the value of the seatingClass property.
     * 
     * @return
     *     possible object is
     *     {@link SeatingClass }
     *     
     */
    public SeatingClass getSeatingClass() {
        return seatingClass;
    }

    /**
     * Sets the value of the seatingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatingClass }
     *     
     */
    public void setSeatingClass(SeatingClass value) {
        this.seatingClass = value;
    }

    /**
     * Gets the value of the sleepers property.
     * 
     * @return
     *     possible object is
     *     {@link Sleepers }
     *     
     */
    public Sleepers getSleepers() {
        return sleepers;
    }

    /**
     * Sets the value of the sleepers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sleepers }
     *     
     */
    public void setSleepers(Sleepers value) {
        this.sleepers = value;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservations() {
        return reservations;
    }

    /**
     * Sets the value of the reservations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservations(String value) {
        this.reservations = value;
    }

    /**
     * Gets the value of the serviceBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceBrand() {
        return serviceBrand;
    }

    /**
     * Sets the value of the serviceBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceBrand(String value) {
        this.serviceBrand = value;
    }

    /**
     * Gets the value of the atocCode property.
     * 
     * @return
     *     possible object is
     *     {@link ATOCCode }
     *     
     */
    public ATOCCode getATOCCode() {
        return atocCode;
    }

    /**
     * Sets the value of the atocCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATOCCode }
     *     
     */
    public void setATOCCode(ATOCCode value) {
        this.atocCode = value;
    }

    /**
     * Gets the value of the topsCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOPSCategory() {
        return topsCategory;
    }

    /**
     * Sets the value of the topsCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOPSCategory(String value) {
        this.topsCategory = value;
    }

    /**
     * Gets the value of the profitCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCentre() {
        return profitCentre;
    }

    /**
     * Sets the value of the profitCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCentre(String value) {
        this.profitCentre = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSector() {
        return sector;
    }

    /**
     * Sets the value of the sector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSector(String value) {
        this.sector = value;
    }

    /**
     * Gets the value of the subSector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSector() {
        return subSector;
    }

    /**
     * Sets the value of the subSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSector(String value) {
        this.subSector = value;
    }

    /**
     * Gets the value of the tractionClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTractionClass() {
        return tractionClass;
    }

    /**
     * Sets the value of the tractionClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTractionClass(String value) {
        this.tractionClass = value;
    }

}
