//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Location on train journey
 * 
 * <p>Java class for ScheduleLocationV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScheduleLocationV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Arrive" type="{http://xml.networkrail.co.uk/ns/2008/Train}LocationTimes"/>
 *           &lt;element name="Depart" type="{http://xml.networkrail.co.uk/ns/2008/Train}LocationTimes"/>
 *           &lt;element name="Pass">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="workingTime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Activity" type="{http://xml.networkrail.co.uk/ns/2008/Train}Activity" maxOccurs="6" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="locationType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="origin"/>
 *             &lt;enumeration value="intermediate"/>
 *             &lt;enumeration value="destination"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="location" use="required" type="{http://xml.networkrail.co.uk/ns/2008/Train}TIPLOCV2" />
 *       &lt;attribute name="callNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="platform" type="{http://xml.networkrail.co.uk/ns/2008/Train}PlatformV2" />
 *       &lt;attribute name="line" type="{http://xml.networkrail.co.uk/ns/2008/Train}RunningLineV2" />
 *       &lt;attribute name="path" type="{http://xml.networkrail.co.uk/ns/2008/Train}RunningLineV2" />
 *       &lt;attribute name="engineeringAllowance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathingAllowance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="performanceAllowance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleLocationV2", propOrder = {
    "arrive",
    "depart",
    "pass",
    "activity"
})
public class ScheduleLocationV2 {

    @XmlElement(name = "Arrive")
    protected LocationTimes arrive;
    @XmlElement(name = "Depart")
    protected LocationTimes depart;
    @XmlElement(name = "Pass")
    protected ScheduleLocationV2 .Pass pass;
    @XmlElement(name = "Activity")
    protected List<String> activity;
    @XmlAttribute(name = "locationType", required = true)
    protected String locationType;
    @XmlAttribute(name = "location", required = true)
    protected String location;
    @XmlAttribute(name = "callNumber", required = true)
    protected BigInteger callNumber;
    @XmlAttribute(name = "platform")
    protected String platform;
    @XmlAttribute(name = "line")
    protected String line;
    @XmlAttribute(name = "path")
    protected String path;
    @XmlAttribute(name = "engineeringAllowance")
    protected String engineeringAllowance;
    @XmlAttribute(name = "pathingAllowance")
    protected String pathingAllowance;
    @XmlAttribute(name = "performanceAllowance")
    protected String performanceAllowance;

    /**
     * Gets the value of the arrive property.
     * 
     * @return
     *     possible object is
     *     {@link LocationTimes }
     *     
     */
    public LocationTimes getArrive() {
        return arrive;
    }

    /**
     * Sets the value of the arrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationTimes }
     *     
     */
    public void setArrive(LocationTimes value) {
        this.arrive = value;
    }

    /**
     * Gets the value of the depart property.
     * 
     * @return
     *     possible object is
     *     {@link LocationTimes }
     *     
     */
    public LocationTimes getDepart() {
        return depart;
    }

    /**
     * Sets the value of the depart property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationTimes }
     *     
     */
    public void setDepart(LocationTimes value) {
        this.depart = value;
    }

    /**
     * Gets the value of the pass property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleLocationV2 .Pass }
     *     
     */
    public ScheduleLocationV2 .Pass getPass() {
        return pass;
    }

    /**
     * Sets the value of the pass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleLocationV2 .Pass }
     *     
     */
    public void setPass(ScheduleLocationV2 .Pass value) {
        this.pass = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getActivity() {
        if (activity == null) {
            activity = new ArrayList<String>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the locationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationType() {
        return locationType;
    }

    /**
     * Sets the value of the locationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationType(String value) {
        this.locationType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the callNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCallNumber() {
        return callNumber;
    }

    /**
     * Sets the value of the callNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCallNumber(BigInteger value) {
        this.callNumber = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the engineeringAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineeringAllowance() {
        return engineeringAllowance;
    }

    /**
     * Sets the value of the engineeringAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineeringAllowance(String value) {
        this.engineeringAllowance = value;
    }

    /**
     * Gets the value of the pathingAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathingAllowance() {
        return pathingAllowance;
    }

    /**
     * Sets the value of the pathingAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathingAllowance(String value) {
        this.pathingAllowance = value;
    }

    /**
     * Gets the value of the performanceAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformanceAllowance() {
        return performanceAllowance;
    }

    /**
     * Sets the value of the performanceAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformanceAllowance(String value) {
        this.performanceAllowance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="workingTime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Pass {

        @XmlAttribute(name = "workingTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar workingTime;

        /**
         * Gets the value of the workingTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getWorkingTime() {
            return workingTime;
        }

        /**
         * Sets the value of the workingTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setWorkingTime(XMLGregorianCalendar value) {
            this.workingTime = value;
        }

    }

}
