//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}OriginalTrainID"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}CurrentTrainID" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}EventTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}LocationStanox"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}GBTTTimestamp" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}WTTTimestamp" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}OriginalLocationStanox" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}OriginalWTTTimestamp" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}PlannedMovementType"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}MovementType"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}EventSource"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}RevisionFlag" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}OffRouteFlag" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}Direction" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}Line" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}Platform" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}Route" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainServiceCode"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}Division"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TOC"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TimetableVariation"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}VariationStatus" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}NextLocationStanox" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}NextReportRunTime" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TerminatedFlag" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}DelayMonitoringFlag" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ReportingLocationStanox" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}AutoExpectedFlag" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainFileAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalTrainID",
    "currentTrainID",
    "eventTimestamp",
    "locationStanox",
    "gbttTimestamp",
    "wttTimestamp",
    "originalLocationStanox",
    "originalWTTTimestamp",
    "plannedMovementType",
    "movementType",
    "eventSource",
    "revisionFlag",
    "offRouteFlag",
    "direction",
    "line",
    "platform",
    "route",
    "trainServiceCode",
    "division",
    "toc",
    "timetableVariation",
    "variationStatus",
    "nextLocationStanox",
    "nextReportRunTime",
    "terminatedFlag",
    "delayMonitoringFlag",
    "reportingLocationStanox",
    "autoExpectedFlag",
    "trainFileAddress"
})
@XmlRootElement(name = "TrainMovementData")
public class TrainMovementData {

    @XmlElement(name = "OriginalTrainID", required = true)
    protected String originalTrainID;
    @XmlElement(name = "CurrentTrainID")
    protected String currentTrainID;
    @XmlElement(name = "EventTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTimestamp;
    @XmlElement(name = "LocationStanox", required = true)
    protected String locationStanox;
    @XmlElement(name = "GBTTTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gbttTimestamp;
    @XmlElement(name = "WTTTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar wttTimestamp;
    @XmlElement(name = "OriginalLocationStanox")
    protected String originalLocationStanox;
    @XmlElement(name = "OriginalWTTTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar originalWTTTimestamp;
    @XmlElement(name = "PlannedMovementType", required = true)
    @XmlSchemaType(name = "string")
    protected TrainMovementType plannedMovementType;
    @XmlElement(name = "MovementType", required = true)
    @XmlSchemaType(name = "string")
    protected TrainMovementType movementType;
    @XmlElement(name = "EventSource", required = true)
    @XmlSchemaType(name = "string")
    protected EventSourceType eventSource;
    @XmlElement(name = "RevisionFlag")
    protected Boolean revisionFlag;
    @XmlElement(name = "OffRouteFlag")
    protected Boolean offRouteFlag;
    @XmlElement(name = "Direction")
    @XmlSchemaType(name = "string")
    protected DirectionType direction;
    @XmlElement(name = "Line")
    protected String line;
    @XmlElement(name = "Platform")
    protected String platform;
    @XmlElement(name = "Route")
    protected String route;
    @XmlElement(name = "TrainServiceCode", required = true)
    protected String trainServiceCode;
    @XmlElement(name = "Division", required = true)
    protected String division;
    @XmlElement(name = "TOC", required = true)
    protected String toc;
    @XmlElement(name = "TimetableVariation")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int timetableVariation;
    @XmlElement(name = "VariationStatus")
    protected String variationStatus;
    @XmlElement(name = "NextLocationStanox")
    protected String nextLocationStanox;
    @XmlElement(name = "NextReportRunTime")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer nextReportRunTime;
    @XmlElement(name = "TerminatedFlag")
    protected Boolean terminatedFlag;
    @XmlElement(name = "DelayMonitoringFlag")
    protected Boolean delayMonitoringFlag;
    @XmlElement(name = "ReportingLocationStanox")
    protected String reportingLocationStanox;
    @XmlElement(name = "AutoExpectedFlag")
    protected Boolean autoExpectedFlag;
    @XmlElement(name = "TrainFileAddress", required = true)
    protected String trainFileAddress;

    /**
     * Gets the value of the originalTrainID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalTrainID() {
        return originalTrainID;
    }

    /**
     * Sets the value of the originalTrainID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalTrainID(String value) {
        this.originalTrainID = value;
    }

    /**
     * Gets the value of the currentTrainID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTrainID() {
        return currentTrainID;
    }

    /**
     * Sets the value of the currentTrainID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTrainID(String value) {
        this.currentTrainID = value;
    }

    /**
     * Gets the value of the eventTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * Sets the value of the eventTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTimestamp(XMLGregorianCalendar value) {
        this.eventTimestamp = value;
    }

    /**
     * Gets the value of the locationStanox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationStanox() {
        return locationStanox;
    }

    /**
     * Sets the value of the locationStanox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationStanox(String value) {
        this.locationStanox = value;
    }

    /**
     * Gets the value of the gbttTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGBTTTimestamp() {
        return gbttTimestamp;
    }

    /**
     * Sets the value of the gbttTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGBTTTimestamp(XMLGregorianCalendar value) {
        this.gbttTimestamp = value;
    }

    /**
     * Gets the value of the wttTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWTTTimestamp() {
        return wttTimestamp;
    }

    /**
     * Sets the value of the wttTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWTTTimestamp(XMLGregorianCalendar value) {
        this.wttTimestamp = value;
    }

    /**
     * Gets the value of the originalLocationStanox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalLocationStanox() {
        return originalLocationStanox;
    }

    /**
     * Sets the value of the originalLocationStanox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalLocationStanox(String value) {
        this.originalLocationStanox = value;
    }

    /**
     * Gets the value of the originalWTTTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalWTTTimestamp() {
        return originalWTTTimestamp;
    }

    /**
     * Sets the value of the originalWTTTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalWTTTimestamp(XMLGregorianCalendar value) {
        this.originalWTTTimestamp = value;
    }

    /**
     * Gets the value of the plannedMovementType property.
     * 
     * @return
     *     possible object is
     *     {@link TrainMovementType }
     *     
     */
    public TrainMovementType getPlannedMovementType() {
        return plannedMovementType;
    }

    /**
     * Sets the value of the plannedMovementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainMovementType }
     *     
     */
    public void setPlannedMovementType(TrainMovementType value) {
        this.plannedMovementType = value;
    }

    /**
     * Gets the value of the movementType property.
     * 
     * @return
     *     possible object is
     *     {@link TrainMovementType }
     *     
     */
    public TrainMovementType getMovementType() {
        return movementType;
    }

    /**
     * Sets the value of the movementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainMovementType }
     *     
     */
    public void setMovementType(TrainMovementType value) {
        this.movementType = value;
    }

    /**
     * Gets the value of the eventSource property.
     * 
     * @return
     *     possible object is
     *     {@link EventSourceType }
     *     
     */
    public EventSourceType getEventSource() {
        return eventSource;
    }

    /**
     * Sets the value of the eventSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSourceType }
     *     
     */
    public void setEventSource(EventSourceType value) {
        this.eventSource = value;
    }

    /**
     * Gets the value of the revisionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRevisionFlag() {
        return revisionFlag;
    }

    /**
     * Sets the value of the revisionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRevisionFlag(Boolean value) {
        this.revisionFlag = value;
    }

    /**
     * Gets the value of the offRouteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOffRouteFlag() {
        return offRouteFlag;
    }

    /**
     * Sets the value of the offRouteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOffRouteFlag(Boolean value) {
        this.offRouteFlag = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionType }
     *     
     */
    public DirectionType getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionType }
     *     
     */
    public void setDirection(DirectionType value) {
        this.direction = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the trainServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainServiceCode() {
        return trainServiceCode;
    }

    /**
     * Sets the value of the trainServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainServiceCode(String value) {
        this.trainServiceCode = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the toc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOC() {
        return toc;
    }

    /**
     * Sets the value of the toc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOC(String value) {
        this.toc = value;
    }

    /**
     * Gets the value of the timetableVariation property.
     * 
     */
    public int getTimetableVariation() {
        return timetableVariation;
    }

    /**
     * Sets the value of the timetableVariation property.
     * 
     */
    public void setTimetableVariation(int value) {
        this.timetableVariation = value;
    }

    /**
     * Gets the value of the variationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariationStatus() {
        return variationStatus;
    }

    /**
     * Sets the value of the variationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariationStatus(String value) {
        this.variationStatus = value;
    }

    /**
     * Gets the value of the nextLocationStanox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextLocationStanox() {
        return nextLocationStanox;
    }

    /**
     * Sets the value of the nextLocationStanox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextLocationStanox(String value) {
        this.nextLocationStanox = value;
    }

    /**
     * Gets the value of the nextReportRunTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNextReportRunTime() {
        return nextReportRunTime;
    }

    /**
     * Sets the value of the nextReportRunTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNextReportRunTime(Integer value) {
        this.nextReportRunTime = value;
    }

    /**
     * Gets the value of the terminatedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTerminatedFlag() {
        return terminatedFlag;
    }

    /**
     * Sets the value of the terminatedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTerminatedFlag(Boolean value) {
        this.terminatedFlag = value;
    }

    /**
     * Gets the value of the delayMonitoringFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelayMonitoringFlag() {
        return delayMonitoringFlag;
    }

    /**
     * Sets the value of the delayMonitoringFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelayMonitoringFlag(Boolean value) {
        this.delayMonitoringFlag = value;
    }

    /**
     * Gets the value of the reportingLocationStanox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingLocationStanox() {
        return reportingLocationStanox;
    }

    /**
     * Sets the value of the reportingLocationStanox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingLocationStanox(String value) {
        this.reportingLocationStanox = value;
    }

    /**
     * Gets the value of the autoExpectedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoExpectedFlag() {
        return autoExpectedFlag;
    }

    /**
     * Sets the value of the autoExpectedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoExpectedFlag(Boolean value) {
        this.autoExpectedFlag = value;
    }

    /**
     * Gets the value of the trainFileAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainFileAddress() {
        return trainFileAddress;
    }

    /**
     * Sets the value of the trainFileAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainFileAddress(String value) {
        this.trainFileAddress = value;
    }

}
