//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}OriginalTrainID"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}EventTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}LocationStanox"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}WTTTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}UIDNumber"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduleStartTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduleEndTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduleSource"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduleType"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}ScheduledWTTID"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TOPSUID"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainPlanOrigin" minOccurs="0"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainPlanOriginTimestamp"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}EventSource"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainCallMode"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TOC"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainServiceCode"/>
 *         &lt;element ref="{http://xml.networkrail.co.uk/ns/2008/Train}TrainFileAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalTrainID",
    "eventTimestamp",
    "locationStanox",
    "wttTimestamp",
    "uidNumber",
    "scheduleStartTimestamp",
    "scheduleEndTimestamp",
    "scheduleSource",
    "scheduleType",
    "scheduledWTTID",
    "topsuid",
    "trainPlanOrigin",
    "trainPlanOriginTimestamp",
    "eventSource",
    "trainCallMode",
    "toc",
    "trainServiceCode",
    "trainFileAddress"
})
@XmlRootElement(name = "TrainActivationData")
public class TrainActivationData {

    @XmlElement(name = "OriginalTrainID", required = true)
    protected String originalTrainID;
    @XmlElement(name = "EventTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTimestamp;
    @XmlElement(name = "LocationStanox", required = true)
    protected String locationStanox;
    @XmlElement(name = "WTTTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar wttTimestamp;
    @XmlElement(name = "UIDNumber", required = true)
    protected String uidNumber;
    @XmlElement(name = "ScheduleStartTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduleStartTimestamp;
    @XmlElement(name = "ScheduleEndTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduleEndTimestamp;
    @XmlElement(name = "ScheduleSource", required = true)
    @XmlSchemaType(name = "string")
    protected ScheduleSource scheduleSource;
    @XmlElement(name = "ScheduleType", required = true)
    @XmlSchemaType(name = "string")
    protected ScheduleType scheduleType;
    @XmlElement(name = "ScheduledWTTID", required = true)
    protected String scheduledWTTID;
    @XmlElement(name = "TOPSUID", required = true)
    protected String topsuid;
    @XmlElement(name = "TrainPlanOrigin")
    protected String trainPlanOrigin;
    @XmlElement(name = "TrainPlanOriginTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar trainPlanOriginTimestamp;
    @XmlElement(name = "EventSource", required = true)
    @XmlSchemaType(name = "string")
    protected EventSourceType eventSource;
    @XmlElement(name = "TrainCallMode", required = true)
    protected String trainCallMode;
    @XmlElement(name = "TOC", required = true)
    protected String toc;
    @XmlElement(name = "TrainServiceCode", required = true)
    protected String trainServiceCode;
    @XmlElement(name = "TrainFileAddress", required = true)
    protected String trainFileAddress;

    /**
     * Gets the value of the originalTrainID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalTrainID() {
        return originalTrainID;
    }

    /**
     * Sets the value of the originalTrainID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalTrainID(String value) {
        this.originalTrainID = value;
    }

    /**
     * Gets the value of the eventTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * Sets the value of the eventTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTimestamp(XMLGregorianCalendar value) {
        this.eventTimestamp = value;
    }

    /**
     * Gets the value of the locationStanox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationStanox() {
        return locationStanox;
    }

    /**
     * Sets the value of the locationStanox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationStanox(String value) {
        this.locationStanox = value;
    }

    /**
     * Gets the value of the wttTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWTTTimestamp() {
        return wttTimestamp;
    }

    /**
     * Sets the value of the wttTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWTTTimestamp(XMLGregorianCalendar value) {
        this.wttTimestamp = value;
    }

    /**
     * Gets the value of the uidNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIDNumber() {
        return uidNumber;
    }

    /**
     * Sets the value of the uidNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIDNumber(String value) {
        this.uidNumber = value;
    }

    /**
     * Gets the value of the scheduleStartTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduleStartTimestamp() {
        return scheduleStartTimestamp;
    }

    /**
     * Sets the value of the scheduleStartTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduleStartTimestamp(XMLGregorianCalendar value) {
        this.scheduleStartTimestamp = value;
    }

    /**
     * Gets the value of the scheduleEndTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduleEndTimestamp() {
        return scheduleEndTimestamp;
    }

    /**
     * Sets the value of the scheduleEndTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduleEndTimestamp(XMLGregorianCalendar value) {
        this.scheduleEndTimestamp = value;
    }

    /**
     * Gets the value of the scheduleSource property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleSource }
     *     
     */
    public ScheduleSource getScheduleSource() {
        return scheduleSource;
    }

    /**
     * Sets the value of the scheduleSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleSource }
     *     
     */
    public void setScheduleSource(ScheduleSource value) {
        this.scheduleSource = value;
    }

    /**
     * Gets the value of the scheduleType property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleType }
     *     
     */
    public ScheduleType getScheduleType() {
        return scheduleType;
    }

    /**
     * Sets the value of the scheduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleType }
     *     
     */
    public void setScheduleType(ScheduleType value) {
        this.scheduleType = value;
    }

    /**
     * Gets the value of the scheduledWTTID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduledWTTID() {
        return scheduledWTTID;
    }

    /**
     * Sets the value of the scheduledWTTID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduledWTTID(String value) {
        this.scheduledWTTID = value;
    }

    /**
     * Gets the value of the topsuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOPSUID() {
        return topsuid;
    }

    /**
     * Sets the value of the topsuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOPSUID(String value) {
        this.topsuid = value;
    }

    /**
     * Gets the value of the trainPlanOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainPlanOrigin() {
        return trainPlanOrigin;
    }

    /**
     * Sets the value of the trainPlanOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainPlanOrigin(String value) {
        this.trainPlanOrigin = value;
    }

    /**
     * Gets the value of the trainPlanOriginTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrainPlanOriginTimestamp() {
        return trainPlanOriginTimestamp;
    }

    /**
     * Sets the value of the trainPlanOriginTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrainPlanOriginTimestamp(XMLGregorianCalendar value) {
        this.trainPlanOriginTimestamp = value;
    }

    /**
     * Gets the value of the eventSource property.
     * 
     * @return
     *     possible object is
     *     {@link EventSourceType }
     *     
     */
    public EventSourceType getEventSource() {
        return eventSource;
    }

    /**
     * Sets the value of the eventSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSourceType }
     *     
     */
    public void setEventSource(EventSourceType value) {
        this.eventSource = value;
    }

    /**
     * Gets the value of the trainCallMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainCallMode() {
        return trainCallMode;
    }

    /**
     * Sets the value of the trainCallMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainCallMode(String value) {
        this.trainCallMode = value;
    }

    /**
     * Gets the value of the toc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOC() {
        return toc;
    }

    /**
     * Sets the value of the toc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOC(String value) {
        this.toc = value;
    }

    /**
     * Gets the value of the trainServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainServiceCode() {
        return trainServiceCode;
    }

    /**
     * Sets the value of the trainServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainServiceCode(String value) {
        this.trainServiceCode = value;
    }

    /**
     * Gets the value of the trainFileAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainFileAddress() {
        return trainFileAddress;
    }

    /**
     * Sets the value of the trainFileAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainFileAddress(String value) {
        this.trainFileAddress = value;
    }

}
