//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type that allows either a headcode or a 10 char train Id
 * 
 * <p>Java class for TrainID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TRUSTTrainId" type="{http://xml.networkrail.co.uk/ns/2008/Train}TRUSTTrainId"/>
 *         &lt;element name="TrainIdentify" type="{http://xml.networkrail.co.uk/ns/2008/Train}TrainIdentity"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainID", propOrder = {
    "trustTrainId",
    "trainIdentify"
})
public class TrainID {

    @XmlElement(name = "TRUSTTrainId")
    protected String trustTrainId;
    @XmlElement(name = "TrainIdentify")
    protected String trainIdentify;

    /**
     * Gets the value of the trustTrainId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRUSTTrainId() {
        return trustTrainId;
    }

    /**
     * Sets the value of the trustTrainId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRUSTTrainId(String value) {
        this.trustTrainId = value;
    }

    /**
     * Gets the value of the trainIdentify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainIdentify() {
        return trainIdentify;
    }

    /**
     * Sets the value of the trainIdentify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainIdentify(String value) {
        this.trainIdentify = value;
    }

}
