//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRUSTRecordType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRUSTRecordType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="AD"/>
 *     &lt;enumeration value="AE"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="DC"/>
 *     &lt;enumeration value="DD"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="DG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRUSTRecordType")
@XmlEnum
public enum TRUSTRecordType {

    AC,
    AD,
    AE,
    AG,
    DC,
    DD,
    DE,
    DG;

    public String value() {
        return name();
    }

    public static TRUSTRecordType fromValue(String v) {
        return valueOf(v);
    }

}
