//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.20 at 07:55:47 PM GMT 
//


package uk.co.networkrail.xml.ns._2008.train;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRUSTDAUpdateTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRUSTDAUpdateTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="S016"/>
 *     &lt;enumeration value="S017"/>
 *     &lt;enumeration value="S018"/>
 *     &lt;enumeration value="S027"/>
 *     &lt;enumeration value="T008"/>
 *     &lt;enumeration value="T009"/>
 *     &lt;enumeration value="T010"/>
 *     &lt;enumeration value="T011"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRUSTDAUpdateTypeType")
@XmlEnum
public enum TRUSTDAUpdateTypeType {

    @XmlEnumValue("S016")
    S_016("S016"),
    @XmlEnumValue("S017")
    S_017("S017"),
    @XmlEnumValue("S018")
    S_018("S018"),
    @XmlEnumValue("S027")
    S_027("S027"),
    @XmlEnumValue("T008")
    T_008("T008"),
    @XmlEnumValue("T009")
    T_009("T009"),
    @XmlEnumValue("T010")
    T_010("T010"),
    @XmlEnumValue("T011")
    T_011("T011");
    private final String value;

    TRUSTDAUpdateTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRUSTDAUpdateTypeType fromValue(String v) {
        for (TRUSTDAUpdateTypeType c: TRUSTDAUpdateTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
